version: "3.7"
services:
  shorten_backend:
    container_name: shorten_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${NODEJS_PUBLIC_PORT}:3000"

    depends_on:
      - shorten_database

  shorten_database:
    image: postgres:16.2
    container_name: shorten_database
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_TITLE}"
    ports:
      - "${DATABASE_PUBLIC_PORT}:5432"
    volumes:
      - shorten_db_data:/var/lib/postgresql/data

volumes:
  shorten_db_data:
    name: shorten_db_data
